name: "largelava"
seeds: 40 # THIS SHOULD BE THE NUMBER OF SEEDS, NOT THE LIST WITH SEEDS!
env: "LavaWorld13x15StochMovement" #"LavaWorld13x15Determ" # "LavaWorld13x15StochMovement" # 
policy: "EpsilonGreedy" # ["EpsilonGreedy"]
epsilon_0: 1.0      # starting value of epsilon eps_0
epsilon_decay: 0.9  # this is parameter beta in eps = eps_0 / n(s)^beta. If beta = 0 we have a fixed epsilon
alpha_0: 0.1        # starting value of alpha
alpha_decay: 0    # parameter omega in alpha = alpha / n(s,a)^omega. If omega = 0 we have a fixed alpha
gamma: 1
num_iter: 10
metric_names: ["episode_returns","episode_lengths"] 