name: "lava_stoch_rewards"
seeds: 20 # THIS SHOULD BE THE NUMBER OF SEEDS, NOT THE LIST WITH SEEDS!
env: "LavaWorld13x15StochRewards" # "LavaWorld13x15Determ" # "LavaWorld5x7StochMovement" # ["WindyGridworldEnv", "EmptyDenseEnv5x5"]
policy: "EpsilonGreedy" # ["EpsilonGreedy"]
epsilon: 1.0
eps_decay: True
alpha: 0.1
gamma: 1
num_iter: 600
metric_names: ["episode_returns","episode_lengths"] 
