name: "lava"
seeds: [0,1] #,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
env: "LavaWorld13x15StochMovement" # "LavaWorld13x15Determ" # "LavaWorld5x7StochMovement" # ["WindyGridworldEnv", "EmptyDenseEnv5x5"]
policy: "EpsilonGreedy" # ["EpsilonGreedy"]
epsilon: 1.0
eps_decay: True
alpha: 0.1
gamma: 1
num_iter: 400
metric_names: ["episode_returns","episode_lengths"] 