name: "test"
seeds: [0,1] #,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
env: "CliffWalkingEnv" # ["WindyGridworldEnv", "EmptyDenseEnv5x5", "CliffWalkingEnv"]
policy: "EpsilonGreedy" # ["EpsilonGreedy"]
epsilon_0: .1     # starting value of epsilon eps_0
epsilon_decay: 0. # this is parameter beta in eps = eps_0 / n(s)^beta. If beta = 0 we have a fixed epsilon
alpha_0: 0.5      # starting value of alpha
alpha_decay: 0.   # parameter omega in alpha = alpha / n(s,a)^omega. If omega = 0 we have a fixed alpha
gamma: 1
num_iter: 10

#only for giving the names in the plot, not for selection of what to record during training
#the number of metric names determines how many of the first defined metrics are attempted to be plotted
#current metrics available: 
#1) episode_returns aggregates over seeds (mean,std)
#2) episode_lengths aggregates over seeds (mean,std)
metric_names: ["episode_returns","episode_lengths"] 